data:
  image: tianon/true
  volumes:
    - /var/www/html

web:
  build: web
  links:
    - php
  ports:
    - "8080:80"
  env_file: .env
  volumes_from:
    - data:ro

php:
  build: php
  links:
    - mysql
    - indexer
  env_file: .env
  volumes_from:
    - data:rw

mysql:
  image: mysql:5.7
  env_file: .env

indexer:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
  environment:
    - cluster.name=akeneo
    - discovery.type=single-node
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
