services:
  data:
    image: tianon/true
    volumes:
    - /var/www/html

  indexer:
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      cluster.name: akeneo
      discovery.type: single-node
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0

  mysql:
    image: mysql:5.7
    env_file: .env

  php:
    build: php
    env_file: .env
    links:
    - mysql
    - indexer
    volumes_from:
    - service:data:rw
    depends_on:
      - data
      - mysql
      - indexer

  queue:
    build: php
    env_file: .env
    command: /opt/launch-daemon.sh
    links:
    - mysql
    - indexer
    volumes_from:
    - service:data:rw
    depends_on:
      - data
      - mysql
      - indexer

  web:
    build: web
    env_file: .env
    links:
    - php
    ports:
    - 8080:80/tcp
    volumes_from:
    - service:data:ro
    depends_on:
    - data
    - php

version: '2.1'